graph_store: kgx.graph.nx_graph.NxGraph

neo4j:
  username: neo4j
  password: neo4j
  host: localhost
  ports:
     bolt: 7687
     http: 7474

ontologies:
  RO: http://purl.obolibrary.org/obo/ro.owl
  BFO: http://purl.obolibrary.org/obo/bfo.owl
  #SEPIO: http://purl.obolibrary.org/obo/sepio.owl

logging:
  level: INFO
  format: '[%(name)s][%(filename)s][%(funcName)20s] %(levelname)s: %(message)s'

jsonld-context:
  biolink: https://raw.githubusercontent.com/biolink/biolink-model/2.2.5/context.jsonld
  monarch_context: https://raw.githubusercontent.com/prefixcommons/biocontext/master/registry/monarch_context.jsonld
  obo_context: https://raw.githubusercontent.com/prefixcommons/biocontext/master/registry/obo_context.jsonld